/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src\bgw\mod.rs:24

    CREATE SCHEMA IF NOT EXISTS pgnats;

    CREATE TABLE IF NOT EXISTS pgnats.subscriptions (
        subject TEXT NOT NULL,
        callback TEXT NOT NULL,
        UNIQUE(subject, callback)
    );
/* </end connected objects> */

/* <begin connected objects> */
-- src\bgw\fdw.rs:22
-- requires:
--   create_subscriptions_table


    CREATE FUNCTION pgnats.enforce_single_pgnats_fdw_server()
    RETURNS event_trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
        fdw_count int;
    BEGIN
        SELECT COUNT(*) INTO fdw_count
        FROM pg_foreign_server s
        JOIN pg_foreign_data_wrapper f ON f.oid = s.srvfdw
        WHERE f.fdwname = 'pgnats_fdw';

        IF fdw_count > 1 THEN
            RAISE EXCEPTION 'Only one server with FDW pgnats_fdw is allowed.';
        END IF;
    END;
    $$;

    CREATE EVENT TRIGGER enforce_single_pgnats_fdw_server_trigger
    ON ddl_command_end
    WHEN TAG IN ('CREATE SERVER')
    EXECUTE FUNCTION pgnats.enforce_single_pgnats_fdw_server();
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:447
-- pgnats::api::nats::nats_delete_file
CREATE  FUNCTION "nats_delete_file"(
	"store" TEXT, /* alloc::string::String */
	"name" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_delete_file_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:343
-- pgnats::api::nats::nats_delete_value
CREATE  FUNCTION "nats_delete_value"(
	"bucket" TEXT, /* alloc::string::String */
	"key" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_delete_value_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:254
-- pgnats::api::nats::nats_get_binary
CREATE  FUNCTION "nats_get_binary"(
	"bucket" TEXT, /* alloc::string::String */
	"key" TEXT /* &str */
) RETURNS bytea /* core::result::Result<core::option::Option<alloc::vec::Vec<u8>>, anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_get_binary_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:405
-- pgnats::api::nats::nats_get_file
CREATE  FUNCTION "nats_get_file"(
	"store" TEXT, /* alloc::string::String */
	"name" TEXT /* &str */
) RETURNS bytea /* core::result::Result<alloc::vec::Vec<u8>, anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_get_file_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:470
-- pgnats::api::nats::nats_get_file_info
CREATE  FUNCTION "nats_get_file_info"(
	"store" TEXT, /* alloc::string::String */
	"name" TEXT /* &str */
) RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"description" TEXT,  /* core::option::Option<alloc::string::String> */
	"metadata" jsonb,  /* pgrx::datum::json::JsonB */
	"headers" jsonb,  /* core::option::Option<pgrx::datum::json::JsonB> */
	"options" jsonb,  /* core::option::Option<pgrx::datum::json::JsonB> */
	"bucket" TEXT,  /* alloc::string::String */
	"nuid" TEXT,  /* alloc::string::String */
	"size" bigint,  /* i64 */
	"chunks" bigint,  /* i64 */
	"modified" TEXT,  /* core::option::Option<alloc::string::String> */
	"digest" TEXT,  /* core::option::Option<alloc::string::String> */
	"delete" bool  /* bool */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_get_file_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:513
-- pgnats::api::nats::nats_get_file_list
CREATE  FUNCTION "nats_get_file_list"(
	"store" TEXT /* alloc::string::String */
) RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"description" TEXT,  /* core::option::Option<alloc::string::String> */
	"metadata" jsonb,  /* pgrx::datum::json::JsonB */
	"headers" jsonb,  /* core::option::Option<pgrx::datum::json::JsonB> */
	"options" jsonb,  /* core::option::Option<pgrx::datum::json::JsonB> */
	"bucket" TEXT,  /* alloc::string::String */
	"nuid" TEXT,  /* alloc::string::String */
	"size" bigint,  /* i64 */
	"chunks" bigint,  /* i64 */
	"modified" TEXT,  /* core::option::Option<alloc::string::String> */
	"digest" TEXT,  /* core::option::Option<alloc::string::String> */
	"delete" bool  /* bool */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_get_file_list_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:292
-- pgnats::api::nats::nats_get_json
CREATE  FUNCTION "nats_get_json"(
	"bucket" TEXT, /* alloc::string::String */
	"key" TEXT /* &str */
) RETURNS json /* core::result::Result<core::option::Option<pgrx::datum::json::Json>, anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_get_json_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:311
-- pgnats::api::nats::nats_get_jsonb
CREATE  FUNCTION "nats_get_jsonb"(
	"bucket" TEXT, /* alloc::string::String */
	"key" TEXT /* &str */
) RETURNS jsonb /* core::result::Result<core::option::Option<pgrx::datum::json::JsonB>, anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_get_jsonb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:361
-- pgnats::api::nats::nats_get_server_info
CREATE  FUNCTION "nats_get_server_info"() RETURNS TABLE (
	"server_id" TEXT,  /* alloc::string::String */
	"server_name" TEXT,  /* alloc::string::String */
	"host" TEXT,  /* alloc::string::String */
	"port" INT,  /* i32 */
	"version" TEXT,  /* alloc::string::String */
	"auth_required" bool,  /* bool */
	"tls_requiered" bool,  /* bool */
	"max_payload" bigint,  /* i64 */
	"proto" "char",  /* i8 */
	"client_id" bigint,  /* i64 */
	"go" TEXT,  /* alloc::string::String */
	"nonce" TEXT,  /* alloc::string::String */
	"connect_urls" jsonb,  /* pgrx::datum::json::JsonB */
	"client_ip" TEXT,  /* alloc::string::String */
	"headers" bool,  /* bool */
	"lame_duck_mode" bool  /* bool */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_get_server_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:273
-- pgnats::api::nats::nats_get_text
CREATE  FUNCTION "nats_get_text"(
	"bucket" TEXT, /* alloc::string::String */
	"key" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<core::option::Option<alloc::string::String>, anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_get_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:9
-- pgnats::api::nats::nats_publish_binary
CREATE  FUNCTION "nats_publish_binary"(
	"subject" TEXT, /* &str */
	"payload" bytea, /* alloc::vec::Vec<u8> */
	"reply" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"headers" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_publish_binary_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:9
-- pgnats::api::nats::nats_publish_binary_stream
CREATE  FUNCTION "nats_publish_binary_stream"(
	"subject" TEXT, /* &str */
	"payload" bytea, /* alloc::vec::Vec<u8> */
	"headers" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_publish_binary_stream_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:55
-- pgnats::api::nats::nats_publish_json
CREATE  FUNCTION "nats_publish_json"(
	"subject" TEXT, /* &str */
	"payload" json, /* pgrx::datum::json::Json */
	"reply" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"headers" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_publish_json_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:55
-- pgnats::api::nats::nats_publish_json_stream
CREATE  FUNCTION "nats_publish_json_stream"(
	"subject" TEXT, /* &str */
	"payload" json, /* pgrx::datum::json::Json */
	"headers" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_publish_json_stream_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:78
-- pgnats::api::nats::nats_publish_jsonb
CREATE  FUNCTION "nats_publish_jsonb"(
	"subject" TEXT, /* &str */
	"payload" jsonb, /* pgrx::datum::json::JsonB */
	"reply" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"headers" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_publish_jsonb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:78
-- pgnats::api::nats::nats_publish_jsonb_stream
CREATE  FUNCTION "nats_publish_jsonb_stream"(
	"subject" TEXT, /* &str */
	"payload" jsonb, /* pgrx::datum::json::JsonB */
	"headers" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_publish_jsonb_stream_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:32
-- pgnats::api::nats::nats_publish_text
CREATE  FUNCTION "nats_publish_text"(
	"subject" TEXT, /* &str */
	"payload" TEXT, /* alloc::string::String */
	"reply" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"headers" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_publish_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:32
-- pgnats::api::nats::nats_publish_text_stream
CREATE  FUNCTION "nats_publish_text_stream"(
	"subject" TEXT, /* &str */
	"payload" TEXT, /* alloc::string::String */
	"headers" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_publish_text_stream_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:178
-- pgnats::api::nats::nats_put_binary
CREATE  FUNCTION "nats_put_binary"(
	"bucket" TEXT, /* alloc::string::String */
	"key" TEXT, /* &str */
	"data" bytea /* alloc::vec::Vec<u8> */
) RETURNS bigint /* core::result::Result<i64, anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_put_binary_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:425
-- pgnats::api::nats::nats_put_file
CREATE  FUNCTION "nats_put_file"(
	"store" TEXT, /* alloc::string::String */
	"name" TEXT, /* &str */
	"content" bytea /* alloc::vec::Vec<u8> */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_put_file_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:216
-- pgnats::api::nats::nats_put_json
CREATE  FUNCTION "nats_put_json"(
	"bucket" TEXT, /* alloc::string::String */
	"key" TEXT, /* &str */
	"data" json /* pgrx::datum::json::Json */
) RETURNS bigint /* core::result::Result<i64, anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_put_json_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:235
-- pgnats::api::nats::nats_put_jsonb
CREATE  FUNCTION "nats_put_jsonb"(
	"bucket" TEXT, /* alloc::string::String */
	"key" TEXT, /* &str */
	"data" jsonb /* pgrx::datum::json::JsonB */
) RETURNS bigint /* core::result::Result<i64, anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_put_jsonb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:197
-- pgnats::api::nats::nats_put_text
CREATE  FUNCTION "nats_put_text"(
	"bucket" TEXT, /* alloc::string::String */
	"key" TEXT, /* &str */
	"data" TEXT /* &str */
) RETURNS bigint /* core::result::Result<i64, anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_put_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:101
-- pgnats::api::nats::nats_request_binary
CREATE  FUNCTION "nats_request_binary"(
	"subject" TEXT, /* &str */
	"payload" bytea, /* alloc::vec::Vec<u8> */
	"timeout" INT /* core::option::Option<i32> */
) RETURNS bytea /* core::result::Result<alloc::vec::Vec<u8>, anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_request_binary_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:139
-- pgnats::api::nats::nats_request_json
CREATE  FUNCTION "nats_request_json"(
	"subject" TEXT, /* &str */
	"payload" json, /* pgrx::datum::json::Json */
	"timeout" INT /* core::option::Option<i32> */
) RETURNS bytea /* core::result::Result<alloc::vec::Vec<u8>, anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_request_json_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:158
-- pgnats::api::nats::nats_request_jsonb
CREATE  FUNCTION "nats_request_jsonb"(
	"subject" TEXT, /* &str */
	"payload" jsonb, /* pgrx::datum::json::JsonB */
	"timeout" INT /* core::option::Option<i32> */
) RETURNS bytea /* core::result::Result<alloc::vec::Vec<u8>, anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_request_jsonb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:120
-- pgnats::api::nats::nats_request_text
CREATE  FUNCTION "nats_request_text"(
	"subject" TEXT, /* &str */
	"payload" TEXT, /* alloc::string::String */
	"timeout" INT /* core::option::Option<i32> */
) RETURNS bytea /* core::result::Result<alloc::vec::Vec<u8>, anyhow::Error> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_request_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:564
-- pgnats::api::nats::nats_subscribe
CREATE  FUNCTION "nats_subscribe"(
	"subject" TEXT, /* alloc::string::String */
	"fn_name" TEXT /* alloc::string::String */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_subscribe_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\nats.rs:599
-- pgnats::api::nats::nats_unsubscribe
CREATE  FUNCTION "nats_unsubscribe"(
	"subject" TEXT, /* alloc::string::String */
	"fn_name" TEXT /* alloc::string::String */
) RETURNS VOID /* core::result::Result<(), anyhow::Error> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nats_unsubscribe_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\bgw\fdw.rs:51
-- pgnats::bgw::fdw::pgnats_fdw_validator
CREATE  FUNCTION "pgnats_fdw_validator"(
	"options" TEXT[], /* alloc::vec::Vec<alloc::string::String> */
	"oid" oid /* pgrx_pg_sys::submodules::oids::Oid */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pgnats_fdw_validator_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\bgw\fdw.rs:13
-- requires:
--   pgnats_fdw_validator


    CREATE FOREIGN DATA WRAPPER pgnats_fdw VALIDATOR pgnats_fdw_validator;
    -- CREATE SERVER nats_fdw_server FOREIGN DATA WRAPPER pgnats_fdw OPTIONS (host 'localhost', port '4222');
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\mod.rs:23
-- pgnats::api::pgnats_reload_conf
CREATE  FUNCTION "pgnats_reload_conf"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pgnats_reload_conf_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\mod.rs:45
-- pgnats::api::pgnats_reload_conf_force
CREATE  FUNCTION "pgnats_reload_conf_force"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pgnats_reload_conf_force_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src\api\mod.rs:63
-- pgnats::api::pgnats_version
CREATE  FUNCTION "pgnats_version"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pgnats_version_wrapper';
/* </end connected objects> */

