name: Rust

on:
  push:
    branches: ["main", "ghactions", "pgpro"]
  pull_request:
    branches: ["main", "pgpro"]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.generate-cache-key.outputs.cache-key }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache pkg-config

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          cache: true
          cache-key: ${{ steps.generate-cache-key.outputs.cache-key }}

      - name: Generate cache key
        id: generate-cache-key
        run: |
          echo "cache-key=${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('.cargo-pgrx-version') }}" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
            ~/.pgrx
          key: ${{ steps.generate-cache-key.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Update pgnats dependencies
        run: cargo update

      - name: Install pgrx
        run: |
          PGRX_VERSION=$(cat .cargo-pgrx-version)
          if ! command -v cargo-pgrx &> /dev/null; then
            cargo install --locked cargo-pgrx --version "$PGRX_VERSION"
          else
            CURRENT_VERSION=$(cargo pgrx --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
            if [ "$CURRENT_VERSION" != "$PGRX_VERSION" ]; then
              echo "Updating cargo-pgrx from $CURRENT_VERSION to $PGRX_VERSION..."
              cargo install --locked cargo-pgrx --version "$PGRX_VERSION" --force
            fi
          fi
          if [ ! -d "$HOME/.pgrx" ]; then
            cargo pgrx init
          fi

  tests:
    name: Tests for Postgres-${{ matrix.pg-version }}
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        pg-version: [13, 14, 15, 16, 17]
    services:
      nats:
        image: nats:alpine
        ports:
          - 4222:4222
        options: --name jetstream

    steps:
      - uses: actions/checkout@v4

      - name: Restart NATS with Jetstream
        run: |
          chmod a+x ${{ github.workspace }}/.github/workflows/nats_entrypoint.sh
          docker cp ${{ github.workspace }}/.github/workflows/nats_entrypoint.sh jetstream:/usr/local/bin/docker-entrypoint.sh
          docker restart jetstream

      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
            ~/.pgrx
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Wait for NATS
        run: timeout 60 sh -c 'until nc -z localhost 4222; do sleep 1; done'

      - name: Run pgrx tests
        run: cargo pgrx test pg${{ matrix.pg-version }}

  clippy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
            ~/.pgrx
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run Clippy
        run: cargo clippy -- -D warnings

  package:
    name: Package for Postgres-${{ matrix.pg-version }}
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        pg-version: [13, 14, 15, 16, 17]

    steps:
      - uses: actions/checkout@v4

      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
            ~/.pgrx
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Get pg_config and extension output path
        id: pgpaths
        run: |
          PG_CONFIG=$(cargo pgrx info pg-config ${{ matrix.pg-version }})
          echo "pg_config=$PG_CONFIG" >> $GITHUB_OUTPUT

          PGRX_ROOT=$(dirname "$(dirname "$PG_CONFIG")")
          echo "pgrx_root=$PGRX_ROOT" >> $GITHUB_OUTPUT

          EXT_PATH=target/release/pgnats-pg${{ matrix.pg-version }}/$PGRX_ROOT/share/postgresql/extension
          echo "ext_path=$EXT_PATH" >> $GITHUB_OUTPUT

          LIB_PATH=target/release/pgnats-pg${{ matrix.pg-version }}/$PGRX_ROOT/lib/postgresql
          echo "lib_path=$LIB_PATH" >> $GITHUB_OUTPUT

      - name: Package extension
        run: cargo pgrx package --pg-config "${{ steps.pgpaths.outputs.pg_config }}"

      - name: Copy built extension artifacts
        run: |
          mkdir -p staging/pg${{ matrix.pg-version }}
          cp -v ${{ steps.pgpaths.outputs.ext_path }}/* staging/pg${{ matrix.pg-version }}/
          cp -v ${{ steps.pgpaths.outputs.lib_path }}/*.so staging/pg${{ matrix.pg-version }}/

      - name: Upload packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pgnats-pg${{ matrix.pg-version }}
          path: staging/pg${{ matrix.pg-version }}
